### ISSUE TITLE
Minor typos in the manual

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#22]
At:

https://github.com/derkork/openscad-graph-editor/blob/master/manual/manual.md

in the "Connecting Nodes" section there is the text:
>You can connect nodes by dragging one of output ports of a node to an input port of another node or vice versa. 
an article is missing, "...dragging one of _the_ output ports..."

Under "Disable Subtree" there is:
>It's node is being displayed slightly translucent in the graph editor to indicate this. 
The first word should be "Its" (possessive), not "It's" (contraction of It is).

Under "Variables" there is:
>Variables allow you to parametrize your graph.
parameterize?

Query --- what is the name of the project? Should it have initial caps? "OpenSCAD Graph Editor" ?

**Comment by derkork** [comment]
First up, thank you very much for taking the time to proofread the manual, I really appreciate it! It is very nice to have a native speaker to check on this 👍 (this its vs it's thing is getting me every time).

Regarding the project name, I have not yet come up with something better than OpenSCAD Graph Editor but I can see how this doesn't roll off the tongue very easily. OSGE doesn't seem to be used much elsewhere, so it would probably be ok to use this as an acronym without causing too much confusion. But if you have a fancy name that suits the project, I'm all ears 😄
