### ISSUE TITLE
Dragging variables with a stylus creates choice menu in the pallet area

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#38]
If you drag a variable into the editing area using a Wacom stylus in Windows the menu appears in the Variables pallet:

![image](https://user-images.githubusercontent.com/3543154/209453357-453fe2c2-c8b6-401d-bc6f-d417c850a6aa.png)

rather than in the editing area as it does when a mouse or trackpad is used:

![image](https://user-images.githubusercontent.com/3543154/209453366-5e2beb0d-2f8d-4456-b43c-07630281c387.png)

**Comment by derkork** [comment]
Hmm i checked this with my Intuous Pro but couldn't reproduce it locally.  Do you have any special settings for the pen? This is how I set up mine:

![image](https://user-images.githubusercontent.com/327257/221237533-ac01fc63-4094-4aee-9543-1b0cafd8fdc3.png)
![image](https://user-images.githubusercontent.com/327257/221237664-381f7f6f-d619-4739-ac26-281b5dc127ae.png)
![image](https://user-images.githubusercontent.com/327257/221237751-1eac63ee-7777-4da7-8dd0-de4382e6a3df.png)

**Comment by WillAdams** [comment]
I'm having this problem on a Samsung Galaxy Book 12 tablet running Windows Build 1703 --- there aren't many settings/options:

![image](https://user-images.githubusercontent.com/3543154/221598736-988971a4-147b-49d4-a3aa-c92762b2703d.png)

![image](https://user-images.githubusercontent.com/3543154/221598787-f5a527a5-b486-412a-9ac8-6c738935aa53.png)

![image](https://user-images.githubusercontent.com/3543154/221598953-1fcb343d-1086-4eb6-868b-3bd24f125f65.png)

![image](https://user-images.githubusercontent.com/3543154/221599139-4f79c770-00e8-42ff-bb3a-6e30e99688d8.png)

![image](https://user-images.githubusercontent.com/3543154/221599190-09213c2e-2713-4773-8091-8204a7e26cc7.png)

![image](https://user-images.githubusercontent.com/3543154/221599236-7b08e45a-1f4a-4133-9e23-b38f44af327d.png)

(had to disable Flicks as discussed previously)

![image](https://user-images.githubusercontent.com/3543154/221599419-39e485d5-114a-46fe-aa87-83672bdaca94.png)

![image](https://user-images.githubusercontent.com/3543154/221599467-3fb692c2-c99d-4b48-8c6a-80c6fe899026.png)

If no one else is having this difficulty it's probably not worth pursuing --- it doesn't happen on the Wacom One on my MacBook.
