### ISSUE TITLE
Add //!OpenSCAD comment at beginning of file and put modules at the top

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#39]
Other tools add the line:

    //!OpenSCAD

and it seems to be more appropriate to have imported modules at the top of the file before variable declarations:

    //!OpenSCAD

    include <C:/Users/willa/OneDrive/Documents/RapCAD/Libraries/gcodepreview.scad>
    include <C:/Users/willa/OneDrive/Documents/RapCAD/Libraries/gcp_joinery.scad>
    
Would that be a viable approach/option?

**Comment by derkork** [comment]
Should be doable. Maybe we could do a "preamble" setting, so you can add arbitrary text to be added before the generated code and this can be set up per project as needed.

**Comment by WillAdams** [comment]
A further consideration here --- should a semi-colon be included at the end of include?

OpenSCAD doesn't mind, but RapCAD does:

![image](https://user-images.githubusercontent.com/3543154/209563254-511353e4-2316-44c2-9c62-c988c854a694.png)
