### ISSUE TITLE
Typos in/suggestions for manual.md

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#5]
In the diagram:
https://github.com/derkork/openscad-graph-editor/blob/master/manual/images/port_colors.png
the first entry "Input geometry for the module" lacks a period, while all the others have one.

At: Split vector2 / vector3
it starts "These node do the opposite of..." and should be: "These nodes do the opposite of..."

At: Using a module
it starts: "To use a module in you main graph..." and should be: "To use a module in your main graph..."

At: Changing the module's name and parameters
the second paragraph starts, "Now the refactoring dialog will open and you can change the module's name, the name and type of any of its parameters." which I find confusing --- would an Oxford comma help? So instead it is, "Now the refactoring dialog will open and you can change the module's name, the name, and type of any of its parameters." maybe also insert "the" in-between and and type, so one has: "Now the refactoring dialog will open and you can change the module's name, the name, and the type of any of its parameters."?

In the bulleted list where you have: "If you rename a parameter this has no effect on the connections to this parameter", better to add a comma to maintain parallelism w/ the preceding bullet? "If you rename a parameter, this has no effect on the connections to this parameter"?

ditto at: "If you add a parameter it will be available as new port for the module's node but no connections will be created for it."

Would a comma be better before _e.g._ in: "After you have refactored a module, you may want to check places where this module is used e.g. to add new connections to an added parameter."?

Incomplete? "Next you have the option how you want to refer to the library." option for? option of?

**Comment by derkork** [comment]
Thank you very much for taking the time to proofread the manual! I have also extended the section on nested loops as you suggested on Discord.
