### ISSUE TITLE
Customization constraints does not take starting value into account

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#61]
If one has a Customizer setup where the Minimum Value is odd, and the Step is set to 2, the Default values will not all be odd as one would expect:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/04d95354-59a8-4341-9eba-46f472901096)

Rather than 3, 5, 7, 9, 11, &c. it shows 4, 6, 8, 10, 12

**Comment by derkork** [comment]
This is a really odd one. The code definitely sets the correct slider range but the slider insists on showing this weird behaviour. Might be an engine bug. I'll try to set up a reproducer and see if it's a general issue or just something weird my editor does.

**Comment by derkork** [comment]
Okay I can confirm this is an engine bug / missing feature. In Godot 3 the min value is not taken into account when calculating the step value.

3.5 version:
```c++
	if (shared->step > 0) {
		p_val = Math::round(p_val / shared->step) * shared->step;
	}
``` 

4.1 version:

```c++
	if (shared->step > 0) {
		p_val = Math::round((p_val - shared->min) / shared->step) * shared->step + shared->min;
	}

```
The only workaround that I have right now is to fall back to a normal number edit in this case so you can at least enter a valid number without hassle.

**Comment by derkork** [comment]
I just committed a fix, I'll build a new version. This should at least enable you to enter a valid default value even though the UI will not prevent you from entering an invalid one. Ultimately I would need to migrate to Godot 4 to really fix this, which will be quite a bit of work and I'm not quite sure if it is worth it.

**Comment by WillAdams** [comment]
Obviously, I'm back to using this, so not impartial, but I'd like to see this program stay up-to-date and continue to be worked on/available.

Thanks again for making it!

**Comment by derkork** [comment]
I am using it myself,  so I will keep it working. I will eventually move it to Godot 4 once support for Godot 3 is dropped. It just doesn't feel proportional to do it to fix this problem, only.

There is still a big overhaul pending for Godot's graph view in 4 and I'd rather migrate after this is done in the engine as it will probably require some rewriting of OSGE.

**Comment by WillAdams** [comment]
That's great to hear!

Agree this is a minor issue --- we'll have to see what the future holds.
