### ISSUE TITLE
Allow duplicating a node with all connections

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#62]
Often, when working on a project, one will need an almost duplicate of a node --- most of the connections will be the same, but one or two will need to be different.

Being able to duplicate the node and maintaining all the connections would make that much more efficient, since it wouldn't be necessary to reconnect the connections which are in common betwixt the twain.

**Comment by derkork** [comment]
So the idea would be you press "duplicate" and it duplicates all selected nodes, offsets them and then adds additional connections to the duplicates, e.g. this:

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/55bda989-07c2-449a-bcaf-9ec5e5288655)


would become this:

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/4c271e36-918f-49ac-b266-2a5d26a54d18)

**Comment by WillAdams** [comment]
Yes, just that --- but usually the node in question is a module.

**Comment by derkork** [comment]
This is surprisingly difficult to do. Duplicating nodes creates new node Ids and I somehow need to map which new node corresponds to which old node to create the connections between nodes that were not duplicated and the new duplicates. This will need a bit of work on the internals.

**Comment by WillAdams** [comment]
If it can be done, I'd really appreciate it, and would find it a big help in more complex projects.

Thanks for considering it!

**Comment by derkork** [comment]
Yes I think it would be a great addition.

**Comment by derkork** [comment]
Will be in release 0.11.0, as soon as the build runs through. Apple is doing another set of shenanigans with their licenses so currently the build aborts when trying to sign the build for OSX. I hope that this gets resolved soon.

**Comment by derkork** [comment]
There we go: https://github.com/derkork/openscad-graph-editor/releases/tag/0.11.0

**Comment by derkork** [comment]
Ah I forgot, it's Ctrl+Shift+D / Cmd+Shift+D if you want the extra connections.
