### ISSUE TITLE
Easier/clearer branching

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#63]
It can be difficult to do more complex problems which require multiple if/then checks.

For example, I worked up a series of checks which worked:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/ca2ef04a-7ed1-4541-affa-2265bd474f66)

but going back to it later when re-writing/drawing/creating this, it didn't seem clear at all, and the arrangement of the nodes/lines wasn't communicating clearly to me.

After a bit of experimentation, I arrived at:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/b076975f-6203-4e36-81e3-7c1e051ba3f6)

which is all true, and I believe works out to the same logically, but some sort of CASE SELECT or other branching option would be welcome.

Just realized that there is an & option --- but didn't see that in the manual --- so maybe this is just a request that & be added to the documentation --- going to try again using it.

Reworking using & seemed clearer:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/0dfb8e7d-e3b0-4e76-b51b-a7bd84a59a6c)

but maybe there's a better option?

**Comment by derkork** [comment]
I have added a paragraph about the boolean operators to the manual. One option to clean this up a little bit would be some string enum node where you can plug in a string and have a range of outputs which are set to true if the input string matches one of the options:

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/00ed30b4-0f80-4564-a586-c245fe1e162d)

This could reduce the 10 comparison nodes to two in your case. You'll still need the boolean operators though as this is the logic for selecting the outputs, but it would at least reduce the visual clutter a bit and using strings as enums is a pretty common use case so I have a feeling this would be a node worth adding.

**Comment by WillAdams** [comment]
Didn't find it at first, since I was expecting it to be under Branching.

Unfortunately, "And" and "Or" are difficult to search for --- maybe put && in the text to make it findable w/ a Search?

**Comment by derkork** [comment]
I have added && and || to the text so its easier to find. Good catch!

**Comment by derkork** [comment]
So we now have this: 

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/c8835a0d-965b-431f-88f8-1628c8fffa75)

Which renders to:

```openscad
if (((kind == "cube") || (kind == "cuboid"))) {
    cube();
}

if ((kind == "sphere")) {
    sphere();
}

```
