### ISSUE TITLE
Make selections easier --- add command to select unused/orphan nodes

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#64]
Often after working on a project for a while one will have various unused nodes:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/b53f16aa-66b1-42f6-8427-e443b86ad14e)

it would be nice to have a button command to select orphan nodes.

**Comment by derkork** [comment]
![image](https://github.com/derkork/openscad-graph-editor/assets/327257/8b96e2a6-39e3-426f-ac97-71664fbc7505)

This should do it, there are some interesting edge cases when nodes are used but also are connected to unused sections.  Can be triggered either with the new button at the bottom of the icon list or with `Ctrl+U/Cmd+U`.
