### ISSUE TITLE
concat doesn't work as expected

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#66]
If one has a concat node:

<img width="417" alt="image" src="https://github.com/derkork/openscad-graph-editor/assets/3543154/b9fe0488-2e34-4c06-951c-f0055695e6cd">

it makes the code:

        opengcodefile(fn = concat(Base_filename, ".nc"));
        opendxffile(fn = concat(Base_filename, ".dxf"));
        opensvgfile(fn = concat(Base_filename, ".svg"));

which doesn't work as expected, since the text which is thus assembled is rendered as:

    ECHO: ["export", "nc"]

Naturally wrapping in str is the fix:

    fn = concat(str(Base_filename, ".nc"));

and this can be done in the interface:

<img width="458" alt="image" src="https://github.com/derkork/openscad-graph-editor/assets/3543154/df2e20e8-471a-4925-af41-c3951cc3b29b">

but I was surprised that it was necessary --- is it strictly necessary that the OpenSCAD code be thus represented? Does one ever concatenate things other than strings?

"concat" doesn't appear in the manual AFAICT, so maybe this is just another documentation request?

**Comment by derkork** [comment]
[`concat`](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Mathematical_Functions#concat) is for concatenating arrays, it's a built-in function of OpenSCAD.  For concatenating strings you can use [`str`](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/String_Functions#str) directly . It also allows you to specify multiple inputs. 

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/edca22c3-7bc3-477d-8738-aea789074d53)

This renders

```openscad
echo(str(base_name, ".nc"));
```

**Comment by WillAdams** [comment]
Ah! That would explain it. Thanks!
