### ISSUE TITLE
Possible to easily dim lines leading to disabled nodes?

### ISSUE THREAD

**Issue by WillAdams** [derkork/openscad-graph-editor#68]
When re-working a module, one thing I've found myself doing regularly was disabling most of the nodes:

![image](https://github.com/derkork/openscad-graph-editor/assets/3543154/8e05a916-edcc-4530-b3d5-61015ea4be43)

but while this helps the 3D preview in OpenCAD, it doesn't make the node/editing view that much more explicable.

If the lines leading to disabled nodes were similarly dimmed, it would be easier to pick out which calculations were being used and which weren't.

**Comment by derkork** [comment]
Would this work?

![image](https://github.com/derkork/openscad-graph-editor/assets/327257/29436762-1820-433a-be97-7d6f3333c36e)

**Comment by WillAdams** [comment]
That looks about perfect! Thanks!

**Comment by derkork** [comment]
Thanks. Just released 0.13.0 which has this.
