### ISSUE TITLE
Failing at the first hurdle

### ISSUE THREAD

**Issue by KeithSloan** [derkork/openscad-graph-editor#9]
Manual says
"You can download the latest release of the OpenSCAD Graph Editor from [GitHub](https://github.com/derkork/openscad-graph-editor/releases) extract it to a convenient location and run the program. No installation procedure is required."

I am on a Mac and have cloned the repro and have a directory openscad-graphic-editor but don't see which if any program to run.
Looking at files with x (execute permission) did not enlighten me.

Tried cloning in /Applications directory with no success.

A post on the OpenScad discussion mailing list seemed to indicate Mac OS is supported.

**Comment by derkork** [comment]
Hey Keith, you will need to download the build for OSX from the release page ([direct link here for your convenience](https://github.com/derkork/openscad-graph-editor/releases/download/0.2.0/MacOSX.zip)), no need to clone the repo.

![image](https://user-images.githubusercontent.com/327257/185474183-f273e33d-17f5-4f45-aa58-472e0d514e10.png)

If you are on a Mac there is an additional hoop to jump through as Apple doesn't like apps that are not notarized. See [this FAQ entry](https://github.com/derkork/openscad-graph-editor/blob/master/manual/faq.md#i-cannot-open-the-app-on-the-mac-it-says-it-is-damaged).

Let me know if that works for you. Enjoy!

**Comment by derkork** [comment]
I have added some clarification to the manual on what to download, so the next person will not encounter this hurdle.
